final products = [
  {
    'id': '0',
    'title': 'Nike AirFlex A1',
    'price': 44.52,
    'imageUrl': 'assets/images/Nike/Nike1.png',
    'company': 'Nike',
    'color': 'red',
    'sizes': [38, 39, 40, 41],
  },
  {
    'id': '1',
    'title': 'Nike ZoomRide A2',
    'price': 55.00,
    'imageUrl': 'assets/images/Nike/Nike2.png',
    'company': 'Nike',
    'color': 'red',
    'sizes': [38, 39, 40, 41, 42],
  },
  {
    'id': '2',
    'title': 'Nike StreetRun A3',
    'price': 62.30,
    'imageUrl': 'assets/images/Nike/Nike3.png',
    'company': 'Nike',
    'color': 'gray',
    'sizes': [38, 39, 40, 41],
  },
  {
    'id': '3',
    'title': 'Nike HyperStep B34',
    'price': 48.75,
    'imageUrl': 'assets/images/Nike/Nike4.png',
    'company': 'Nike',
    'color': 'blue',
    'sizes': [39, 40, 41, 42],
  },
  {
    'id': '4',
    'title': 'Nike CloudSprint B35',
    'price': 52.00,
    'imageUrl': 'assets/images/Nike/Nike5.png',
    'company': 'Nike',
    'color': 'red',
    'sizes': [38, 39, 40, 41],
  },
  {
    'id': '5',
    'title': 'Adidas NovaBoost 1',
    'price': 45.99,
    'imageUrl': 'assets/images/adidas/adidas1.png',
    'company': 'Adidas',
    'color': 'blue',
    'sizes': [38, 39, 40, 41, 42],
  },
  {
    'id': '6',
    'title': 'Adidas StreetRacer 2',
    'price': 58.50,
    'imageUrl': 'assets/images/adidas/adidas2.png',
    'company': 'Adidas',
    'color': 'black',
    'sizes': [38, 39, 40, 41],
  },
  {
    'id': '7',
    'title': 'Adidas PowerStride 3',
    'price': 42.00,
    'imageUrl': 'assets/images/adidas/adidas3.png',
    'company': 'Adidas',
    'color': 'white',
    'sizes': [39, 40, 41, 42],
  },
  {
    'id': '8',
    'title': 'Adidas UltraRun X',
    'price': 65.25,
    'imageUrl': 'assets/images/adidas/adidas4.png',
    'company': 'Adidas',
    'color': 'blue',
    'sizes': [38, 39, 40, 41],
  },
  {
    'id': '9',
    'title': 'Adidas CloudStep 5',
    'price': 47.80,
    'imageUrl': 'assets/images/adidas/adidas5.png',
    'company': 'Adidas',
    'color': 'black',
    'sizes': [38, 39, 40, 41, 42],
  },
  {
    'id': '10',
    'title': 'Bata ComfortWalk 1',
    'price': 28.95,
    'imageUrl': 'assets/images/Bata/bata1.png',
    'company': 'Bata',
    'color': 'black',
    'sizes': [38, 39, 40, 41],
  },
  {
    'id': '11',
    'title': 'Bata StreetEase 2',
    'price': 32.50,
    'imageUrl': 'assets/images/Bata/bata2.png',
    'company': 'Bata',
    'color': 'black',
    'sizes': [39, 40, 41, 42],
  },
  {
    'id': '12',
    'title': 'Bata FlexiRide 3',
    'price': 35.00,
    'imageUrl': 'assets/images/Bata/bata3.png',
    'company': 'Bata',
    'color': 'pink',
    'sizes': [38, 39, 40, 41],
  },
  {
    'id': '13',
    'title': 'Bata LightStep 4',
    'price': 29.99,
    'imageUrl': 'assets/images/Bata/bata4.png',
    'company': 'Bata',
    'color': 'white',
    'sizes': [38, 39, 40, 41, 42],
  },
  {
    'id': '14',
    'title': 'Bata UltraCush 5',
    'price': 38.75,
    'imageUrl': 'assets/images/Bata/bata5.png',
    'company': 'Bata',
    'color': 'blue',
    'sizes': [39, 40, 41],
  },
  {
    'id': '15',
    'title': 'Puma SwiftRun 1',
    'price': 72.00,
    'imageUrl': 'assets/images/puma/puma1.png',
    'company': 'Puma',
    'color': 'green',
    'sizes': [38, 39, 40, 41, 42],
  },
  {
    'id': '16',
    'title': 'Puma AeroDash 2',
    'price': 68.50,
    'imageUrl': 'assets/images/puma/puma2.png',
    'company': 'Puma',
    'color': 'yellow',
    'sizes': [38, 39, 40, 41],
  },
  {
    'id': '17',
    'title': 'Puma PulseRide 3',
    'price': 75.99,
    'imageUrl': 'assets/images/puma/puma3.png',
    'company': 'Puma',
    'color': 'blue',
    'sizes': [39, 40, 41, 42],
  },
  {
    'id': '18',
    'title': 'Puma HyperFlow 4',
    'price': 82.00,
    'imageUrl': 'assets/images/puma/puma4.png',
    'company': 'Puma',
    'color': 'blue',
    'sizes': [38, 39, 40, 41],
  },
  {
    'id': '19',
    'title': 'Puma SpeedCore 5',
    'price': 79.25,
    'imageUrl': 'assets/images/puma/puma5.png',
    'company': 'Puma',
    'color': 'white',
    'sizes': [38, 39, 40, 41, 42],
  },
  {
    'id': '20',
    'title': 'Lotto FlexRun 1',
    'price': 55.00,
    'imageUrl': 'assets/images/lotto/lotto1.png',
    'company': 'Lotto',
    'color': 'white',
    'sizes': [38, 39, 40, 41],
  },
  {
    'id': '21',
    'title': 'Lotto ProStride 2',
    'price': 515.00,
    'imageUrl': 'assets/images/lotto/lotto2.png',
    'company': 'Lotto',
    'color': 'red',
    'sizes': [38, 39, 40, 41],
  },
  {
    'id': '22',
    'title': 'Lotto TerraGrip 3',
    'price': 60.75,
    'imageUrl': 'assets/images/lotto/lotto3.png',
    'company': 'Lotto',
    'color': 'blue',
    'sizes': [39, 40, 41, 42],
  },
];
